### ISSUE TITLE
Integration tests doesn't work locally

### ISSUE THREAD

**Issue by foal** [ArcBees/gwtchosen#253]
Follow the instruction from the mail page and 

```
C:\Development\work\repo\github\gwtchosen>cd integration-test

C:\Development\work\repo\github\gwtchosen\integration-test>mvn gwt:run -Pintegration-test
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building integration-test 2.2.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] >>> gwt-maven-plugin:2.7.0:run (default-cli) > process-classes @ integration-test >>>
[INFO]
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-maven) @ integration-test ---
[INFO]
[INFO] --- maven-checkstyle-plugin:2.13:checkstyle (validate) @ integration-test ---
[INFO] Starting audit...
Audit done.

[INFO]
[INFO] --- port-allocator-maven-plugin:1.2:allocate-ports (default) @ integration-test ---
[INFO] Assigning port '56202' to property 'allocated-port'
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ integration-test ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ integration-test ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] <<< gwt-maven-plugin:2.7.0:run (default-cli) < process-classes @ integration-test <<<
[INFO]
[INFO] --- gwt-maven-plugin:2.7.0:run (default-cli) @ integration-test ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.227 s
[INFO] Finished at: 2015-08-06T08:50:42+02:00
[INFO] Final Memory: 30M/464M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:gwt-maven-plugin:2.7.0:run (default-cli) on project integration-test: The parameters 'runTarget' for goal org.codehaus.mojo:gwt-maven-plugin:2.7.0:run are missing or invalid -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginParameterException
```

**Comment by foal** [comment]
```
C:\Development\work\repo\github\gwtchosen\integration-test>mvn -version
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T13:57:37+02:00)
Maven home: C:\Development\Apache\maven\bin\..
Java version: 1.8.0_51, vendor: Oracle Corporation
Java home: C:\Development\Oracle\JDK\Java\jre
Default locale: en_US, platform encoding: Cp1251
OS name: "windows 8.1", version: "6.3", arch: "amd64", family: "dos"
```

**Comment by meriouma** [comment]
The command to run the tests is `mvn clean verify -Pintegration-test` inside the integration-test folder, although we will look at why debugging the integration tests with `gwt-run` doesn't work anymore

**Comment by foal** [comment]
Ok, Now I have a looot of exceptions in the log, but the important is only one :)

```
doubleBackstroke_removeLastOption(ChosenIT)  Time elapsed: 0 sec  <<< ERROR!
java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see http://code.google.com/p/selenium/wiki/ChromeDriver. The latest version can be downloaded from http://chromedriver.storage.googleapis.com/index.html
        at com.google.common.base.Preconditions.checkState(Preconditions.java:197)
        at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:105)
        at org.openqa.selenium.chrome.ChromeDriverService.createDefaultService(ChromeDriverService.java:89)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:106)
        at ChosenIT.<init>(ChosenIT.java:77)
```

So which version of a chrome driver I should use?

**Comment by meriouma** [comment]
Version 2.17 : http://chromedriver.storage.googleapis.com/index.html?path=2.17/
Check https://sites.google.com/a/chromium.org/chromedriver/ for more informations

**Comment by foal** [comment]
Now it works. Thank you!
```
mvn clean verify -Pintegration-test -Dwebdriver.chrome.driver="C:\Program Files (x86)\Google\Chrome\Application\chromedriver.exe"
```
