### ISSUE TITLE
Failed to upgrade from GWT 2.7.0 to 2.8.0

### ISSUE THREAD

**Issue by fpizzichillo** [ArcBees/gwtchosen#306]
Hi communit. I've got this error when i tried to use gwt 2.8.0
 Checking rule <replace-with class='com.arcbees.chosen.client.NotSupportedChosenImpl'/>
[INFO]                   [WARN] Unknown type 'com.arcbees.chosen.client.ChosenImpl' specified in deferred binding rule
[INFO]                Checking rule <replace-with class='com.arcbees.chosen.client.ChosenImpl'/>

The class NotSupportedChosenImpl is not present in the project. Any hint?

Regards

**Comment by susspectsoftware-dev** [comment]
Anyone have any ideas on this. BEc I can't get it working

**Comment by susspectsoftware-dev** [comment]
com.googlecode.gwt.test.exceptions.ReflectionException: UiBinder error while setting properties for 'ChosenListBox'
	at com.googlecode.gwt.test.uibinder.UiBinderBeanUtils.populateObject(UiBinderBeanUtils.java:78)
	at com.googlecode.gwt.test.uibinder.UiObjectTag.startTag(UiObjectTag.java:285)
	at com.googlecode.gwt.test.uibinder.UiTagBuilder.createUiTag(UiTagBuilder.java:153)
	at com.googlecode.gwt.test.uibinder.UiTagBuilder.startTag(UiTagBuilder.java:123)
	at com.googlecode.gwt.test.uibinder.UiXmlContentHandler.startElement(UiXmlContentHandler.java:68)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at com.googlecode.gwt.test.uibinder.UiBinderParser.createUiComponent(UiBinderParser.java:48)
	at com.googlecode.gwt.test.uibinder.UiBinderInvocationHandler.createAndBindUi(UiBinderInvocationHandler.java:83)
	at com.googlecode.gwt.test.uibinder.UiBinderInvocationHandler.invoke(UiBinderInvocationHandler.java:34)
	at com.sun.proxy.$Proxy94.createAndBindUi(Unknown Source)
	at com.celertech.orderrouting.webtraderlite.client.trading.desktop.fx.price.rfq.FxRfqInputWidgetViewImpl.<init>(FxRfqInputWidgetViewImpl.java:203)
	at com.celertech.orderrouting.webtraderlite.client.trading.desktop.fx.price.rfq.FxInverseRfqTest.setup(FxInverseRfqTest.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.jukito.InjectedStatement.evaluate(InjectedStatement.java:96)
	at org.jukito.InjectedBeforeStatements.evaluate(InjectedBeforeStatements.java:49)
	at org.jukito.InjectedAfterStatements.evaluate(InjectedAfterStatements.java:52)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.jukito.JukitoRunner.run(JukitoRunner.java:197)
	at com.googlecode.gwt.test.internal.junit.AbstractGwtRunner.run(AbstractGwtRunner.java:44)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.commons.beanutils.PropertyUtilsBean.invokeMethod(PropertyUtilsBean.java:2170)
	at org.apache.commons.beanutils.PropertyUtilsBean.setSimpleProperty(PropertyUtilsBean.java:2151)
	at org.apache.commons.beanutils.PropertyUtilsBean.setNestedProperty(PropertyUtilsBean.java:1957)
	at org.apache.commons.beanutils.PropertyUtilsBean.setProperty(PropertyUtilsBean.java:2064)
	at org.apache.commons.beanutils.BeanUtilsBean.setProperty(BeanUtilsBean.java:1017)
	at org.apache.commons.beanutils.BeanUtilsBean.populate(BeanUtilsBean.java:830)
	at com.googlecode.gwt.test.uibinder.UiBinderBeanUtils.populateObject(UiBinderBeanUtils.java:75)
	... 48 more
Caused by: java.lang.NoSuchMethodError: com.google.gwt.query.client.GQuery.$(Lcom/google/gwt/dom/client/Element;)Lcom/google/gwt/query/client/GQuery;
	at com.arcbees.chosen.client.gwt.ChosenListBox.getChosenElement(ChosenListBox.java:333)
	at com.arcbees.chosen.client.gwt.ChosenListBox.getStyleElement(ChosenListBox.java:741)
	at com.google.gwt.user.client.ui.UIObject.setStyleName(UIObject.java:733)
	... 59 more

            "com.googlecode.gwtquery:gwtquery:1.5-beta1",
            "com.arcbees:gwtchosen:3.0.1",
